"""
faa_cxer_ng — ATC conversation error detection with NO ground truth.

Unlike FAA_CxER (which judges an ASR hypothesis against a known-correct
reference transcript), this package has no reference to compare against:
the input is a synthetic multi-turn pilot/controller conversation (text
generated by another LLM from real ASRS incident narratives), and the task
is to find operationally significant communication errors — wrong
callsigns, missed or incorrect readbacks, hearback failures, ambiguous
phraseology — using only the conversation itself.

See the top-level README.md for the full pipeline explanation and how
this differs from the older prototypes it replaces.
"""

__version__ = "0.1.0"
